services:
  commentapi:
    image: ${DOCKER_REGISTRY-}commentapi
    build:
      context: .
      dockerfile: CommentAPI/Dockerfile
    ports:
      - "8080:8080" # HTTP
      - "8081:8081" # HTTPS
    environment:
      SECRET_KEY: "YAMETEKIDASAIIIIYAMETEKIDASAIIII"
      ISSUER: "BACK"
      AUDIENCE: "FRONT"
      EXPIRES_DAYS: "3"
